/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.Cls_Cabecera;
import Datos.Cls_Conexion;
import static Formularios.Frm_Factura.txt_codigo_factura;
import Vistas.Reportes;
import Vistas.Reportes_ventas;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author USUARIO
 */
public class Frm_Reporte_Ventas extends javax.swing.JInternalFrame {
    //variable que permite saber que eleccion tuvo el combo para imprimir
    int opcion;
    /**
     * Creates new form Frm_Reporte_Ventas
     */
    public Frm_Reporte_Ventas() {
        initComponents();
        this.setTitle("Reportes de Ventas");
        Cls_Cabecera c1=new Cls_Cabecera();
        c1.CargarDatos(tbl_ventas);
        Cls_Conexion cargar = new Cls_Conexion();
        cargar.ConsultarTotalFecha("SELECT SUM(FAC_TOTAL) AS TOTAL FROM factura_cabecera_tb ").toString();

        Calendar c2 = new GregorianCalendar();
        Date_Inicio.setCalendar(c2);
        Date_Fin.setCalendar(c2);
        opcion = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ventas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Combo_Estado = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Date_Inicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        Date_Fin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btn_imprimir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbl_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ventas);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("TOTAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda Grupal"));

        Combo_Estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODO", "POR COBRAR", "COBRADA", "ANULADA" }));
        Combo_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_EstadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Fecha de Inicio:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Fecha de Fin:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Estado:");

        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Date_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Date_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Combo_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Combo_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(btn_imprimir))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(Date_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(Date_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda Unitaria"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Busqueda:");

        txt_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busquedaActionPerformed(evt);
            }
        });
        txt_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String capturarfechainicio(){
    int dia = Date_Inicio.getCalendar().get(Calendar.DAY_OF_MONTH);
    int mes = Date_Inicio.getCalendar().get(Calendar.MONTH)+1;
    int año = Date_Inicio.getCalendar().get(Calendar.YEAR) ;
    String fecha = String.valueOf(año)+"-"+String.valueOf(mes)+"-"+String.valueOf(dia);
    return fecha;
    }
    private String capturarfechafin(){
    int dia = Date_Fin.getCalendar().get(Calendar.DAY_OF_MONTH);
    int mes = Date_Fin.getCalendar().get(Calendar.MONTH)+1;
    int año = Date_Fin.getCalendar().get(Calendar.YEAR) ;
    String fecha2 = String.valueOf(año)+"-"+String.valueOf(mes)+"-"+String.valueOf(dia);
    return fecha2;
    }
    
    
    private void Combo_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_EstadoActionPerformed
      String valor=String.valueOf(Combo_Estado.getSelectedItem());
        if ("TODO".equals(valor)){
        Cls_Cabecera c1=new Cls_Cabecera();
        c1.CargarDatos(tbl_ventas);
        Cls_Conexion cargar = new Cls_Conexion();
        cargar.ConsultarTotalFecha("SELECT SUM(FAC_TOTAL) AS TOTAL FROM factura_cabecera_tb ").toString();
        opcion = 0;
        }
        if ("POR COBRAR".equals(valor)){
        Cls_Cabecera cargarfecha = new Cls_Cabecera();
        String inicio = capturarfechainicio();
        String fin = capturarfechafin();
        String estado = "POR COBRAR";
        cargarfecha.CargarDatosporfecha(tbl_ventas, inicio, fin, estado);
        Cls_Conexion cargar = new Cls_Conexion();
        cargar.ConsultarTotalFecha("SELECT SUM(FAC_TOTAL) AS TOTAL FROM factura_cabecera_tb WHERE FAC_FECHA BETWEEN'"+inicio+"'AND'"+fin+"'and FAC_ESTADO='"+estado+"'").toString();
        opcion = 1;
        }
         if ("COBRADA".equals(valor)){
        Cls_Cabecera cargarfecha = new Cls_Cabecera();
        String inicio = capturarfechainicio();
        String fin = capturarfechafin();
        String estado = "COBRADA";
        cargarfecha.CargarDatosporfecha(tbl_ventas, inicio, fin, estado);
        Cls_Conexion cargar = new Cls_Conexion();
        cargar.ConsultarTotalFecha("SELECT SUM(FAC_TOTAL) AS TOTAL FROM factura_cabecera_tb WHERE FAC_FECHA BETWEEN'"+inicio+"'AND'"+fin+"'and FAC_ESTADO='"+estado+"'").toString();
        opcion = 2;
        }
        if ("ANULADA".equals(valor)){
        Cls_Cabecera cargarfecha = new Cls_Cabecera();
        String inicio = capturarfechainicio();
        String fin = capturarfechafin();
        String estado = "ANULADA";
        cargarfecha.CargarDatosporfecha(tbl_ventas, inicio, fin, estado);
        Cls_Conexion cargar = new Cls_Conexion();
        cargar.ConsultarTotalFecha("SELECT SUM(FAC_TOTAL) AS TOTAL FROM factura_cabecera_tb WHERE FAC_FECHA BETWEEN'"+inicio+"'AND'"+fin+"'and FAC_ESTADO='"+estado+"'").toString();
        opcion = 3;
        }
    }//GEN-LAST:event_Combo_EstadoActionPerformed

    private void tbl_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ventasMouseClicked
        String [] opciones = {"EDITAR ESTADO","IMPRIMIR","CANCELAR"};
        int seleccion= JOptionPane.showOptionDialog(null,"Seleccione una opcion", "OPCIONES", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones);
        if (seleccion==0){
            String [] estados = {"POR COBRAR","COBRADA","ANULADA"};
            String resp = (String)JOptionPane.showInputDialog(null,"Seleccione un estado","Tipo de Estado",JOptionPane.DEFAULT_OPTION,null,estados,estados[0]);
            if (resp!=null){ 
                if(tbl_ventas.getSelectedRow()>=0){
                  String [] factura_codigo={
    //                   //obtiene el codigo de la factura
                        String.valueOf(tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(),0)),
                };
                //Actualiza la factura con el nuevo estado
                Cls_Cabecera estado = new Cls_Cabecera();
                estado.ActualizarEstado(Integer.parseInt(factura_codigo[0]),resp);
                JOptionPane.showMessageDialog(null,"Usted a modificado La Factura N° "+factura_codigo[0]+ " al Estado de :"+resp+" .");
                //refresca la tabla
                Cls_Cabecera c1=new Cls_Cabecera();
                c1.CargarDatos(tbl_ventas);
                }
            }    
        }
       if (seleccion==1){
            if(tbl_ventas.getSelectedRow()>=0){
              String [] factura_codigo={
//                   //obtiene el codigo de la factura
                        String.valueOf(tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(),0)),
                };
            try {
                Vistas.Reportes re = new Reportes();
                int reporteFactura = re.reporteFactura(Integer.parseInt(factura_codigo[0]));
            } catch (JRException ex) {
                Logger.getLogger(Frm_Factura.class.getName()).log(Level.SEVERE,null,ex);
            }catch (SQLException ex) {
                Logger.getLogger(Frm_Factura.class.getName()).log(Level.SEVERE,null,ex);

            }
            }
        }     
    }//GEN-LAST:event_tbl_ventasMouseClicked

    private void txt_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaKeyReleased
        Cls_Cabecera unitarios = new Cls_Cabecera();
        unitarios.CargarDatosUnitarios(tbl_ventas, txt_busqueda.getText());
        txt_total.setText(" ");
    }//GEN-LAST:event_txt_busquedaKeyReleased

    private void txt_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquedaActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
      String valor=String.valueOf(Combo_Estado.getSelectedItem());
      String inicio = capturarfechainicio();
        String fin = capturarfechafin();
       try {
                   Vistas.Reportes_ventas re = new Reportes_ventas();
                int reporteVentas = re.reporteVentas(inicio,fin,valor,txt_total.getText());
            } catch (JRException ex) {
                Logger.getLogger(Frm_Factura.class.getName()).log(Level.SEVERE,null,ex);
            }catch (SQLException ex) {
                Logger.getLogger(Frm_Factura.class.getName()).log(Level.SEVERE,null,ex);

            
        
        }
        
    }//GEN-LAST:event_btn_imprimirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_Estado;
    private com.toedter.calendar.JDateChooser Date_Fin;
    private com.toedter.calendar.JDateChooser Date_Inicio;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ventas;
    private javax.swing.JTextField txt_busqueda;
    public static javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
