/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.Cls_Cabecera;
import Clases.Cls_Detalle;
import Datos.Cls_Conexion;
import static Formularios.Frm_Menu.desktopPane;
import Vistas.Reportes;
import java.beans.PropertyVetoException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USUARIO
 */
public class Frm_Factura extends javax.swing.JInternalFrame {
   //variable contador de posiciones para tabla de detalle
    public static int i;
    public static String matriz [][] ;
    boolean banderaborrar;
    public static double total;
    int porcentaje;
    public static boolean banderacliente;
    
    
    /**
     * Creates new form Frm_Factura
     */
    public Frm_Factura() {
        initComponents();
        this.setTitle("Factura");
        i=0;
        //Tamaño de matriz
        matriz = new String [16][5];
        banderaborrar=false;
        //carga valor al label por defecto con cero
        total=0;
        lbl_total.setText(Double.toString(total));
        //carga la fecha del sistema por defecto
        Calendar c2 = new GregorianCalendar();
        txt_fecha.setCalendar(c2);
        porcentaje=0;
        Cls_Conexion cargar = new Cls_Conexion();
        cargar.ConsultaNumero("Select MAX(FAC_CODIGO)+1 as MAXIMO  from factura_cabecera_tb").toString();
        //badera del cliente en false
        banderacliente=false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        btn_buscar_cliente = new javax.swing.JButton();
        txt_fecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detalle = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_codigo_factura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_buscar_productos = new javax.swing.JButton();
        btn_venta = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Combo_precio = new javax.swing.JComboBox();
        btn_activar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente"));

        jLabel1.setText("Señor(es) :");

        txt_nombre.setEditable(false);
        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setText("Cedula/Ruc :");

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setText("Fecha :");

        jLabel4.setText("Direccion:");

        txt_direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_buscar_cliente.setText("Buscar Cliente");
        btn_buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_nombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_buscar_cliente))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbl_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descripcion", "V.Unitario", "V.Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_detalle);
        if (tbl_detalle.getColumnModel().getColumnCount() > 0) {
            tbl_detalle.getColumnModel().getColumn(0).setMinWidth(100);
            tbl_detalle.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbl_detalle.getColumnModel().getColumn(0).setMaxWidth(100);
            tbl_detalle.getColumnModel().getColumn(1).setMinWidth(350);
            tbl_detalle.getColumnModel().getColumn(1).setPreferredWidth(350);
            tbl_detalle.getColumnModel().getColumn(1).setMaxWidth(350);
            tbl_detalle.getColumnModel().getColumn(2).setMinWidth(100);
            tbl_detalle.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbl_detalle.getColumnModel().getColumn(2).setMaxWidth(100);
            tbl_detalle.getColumnModel().getColumn(3).setMinWidth(100);
            tbl_detalle.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbl_detalle.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total a Pagar");

        lbl_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_total.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.getAccessibleContext().setAccessibleName("Total a Pagar :");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));

        jLabel7.setFont(new java.awt.Font("Meiryo", 1, 14)); // NOI18N
        jLabel7.setText("RUC:");

        jLabel8.setFont(new java.awt.Font("Meiryo", 1, 14)); // NOI18N
        jLabel8.setText("N °:");

        jLabel9.setFont(new java.awt.Font("Meiryo", 1, 14)); // NOI18N
        jLabel9.setText("0102830379001");
        jLabel9.setToolTipText("");

        txt_codigo_factura.setEditable(false);
        txt_codigo_factura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_codigo_factura.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        jLabel6.setText("Forja Mueble ");

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 3, 12)); // NOI18N
        jLabel10.setText("Arte y Diseño");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(83, 83, 83))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_codigo_factura))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_codigo_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_buscar_productos.setText("PRODUCTOS");
        btn_buscar_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_productosActionPerformed(evt);
            }
        });

        btn_venta.setText("Realize Venta");
        btn_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventaActionPerformed(evt);
            }
        });

        jLabel12.setText("Tipo de Precio:");

        Combo_precio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0%", "25%", "40%" }));
        Combo_precio.setEnabled(false);
        Combo_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_precioActionPerformed(evt);
            }
        });

        btn_activar.setText("Activar");
        btn_activar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_activarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(btn_activar)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Combo_precio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_buscar_productos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_venta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btn_activar))
                .addGap(18, 18, 18)
                .addComponent(Combo_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_buscar_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(btn_venta)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_clienteActionPerformed
         Frm_Buscar_Cliente b= new Frm_Buscar_Cliente();
         Frm_Menu.desktopPane.add(b);
         b.toFront();
         b.setVisible(true);
         b.setLocation(400,010);       
    }//GEN-LAST:event_btn_buscar_clienteActionPerformed

    private void btn_buscar_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_productosActionPerformed
       
        Frm_Buscar_Producto b= new Frm_Buscar_Producto();
        Frm_Menu.desktopPane.add(b);
        b.toFront();
        b.setVisible(true);
        b.setLocation(545,168);
//        i=i+1;
    }//GEN-LAST:event_btn_buscar_productosActionPerformed

    private void Combo_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_precioActionPerformed
        String valor=String.valueOf(Combo_precio.getSelectedItem());
        if ("0%".equals(valor)){   
            porcentaje=0;
            total=0;
            for (int x=0; x < i; x++){
                double v_unitario= Double.parseDouble(matriz[x][3]);
                //redondeo de numeros
                double aux= Math.rint(v_unitario*100)/100;
                v_unitario=aux;
                //se asigna el valor unitario a la tabla
                tbl_detalle.setValueAt(v_unitario, x, 2);
                int cantidad = Integer.parseInt(matriz[x][1]);
                double total_item = v_unitario*cantidad;
                //redondeo de numeros
                double aux1= Math.rint(total_item*100)/100;
                total_item=aux1;
                //se asigna el valor total de item a la tabla
                tbl_detalle.setValueAt(total_item, x, 3);
                //calcula valor total
                total=total+total_item;
                double aux2= Math.rint(total*100)/100;
                total=aux2;
            }
            //visualiza el total en el label
            lbl_total.setText(Double.toString(total)); 
        }
        if ("25%".equals(valor)){
            porcentaje =25;
            total=0;
            for (int x=0; x < i; x++){
                double v_unitario= Double.parseDouble(matriz[x][3]);
                double v_25=v_unitario*0.25;
                v_unitario=v_unitario+v_25;
                //redondeo de numeros
                double aux= Math.rint(v_unitario*100)/100;
                v_unitario=aux;
                //se asigna el valor unitario a la tabla
                tbl_detalle.setValueAt(v_unitario, x, 2);
                int cantidad = Integer.parseInt(matriz[x][1]);
                double total_item = v_unitario*cantidad;
                //redondeo de numeros
                double aux1= Math.rint(total_item*100)/100;
                total_item=aux1;
                //se asigna el valor total de item a la tabla
                tbl_detalle.setValueAt(total_item, x, 3);
                //se asigna el valor total de item a la tabla
                tbl_detalle.setValueAt(total_item, x, 3);
                //calcula valor total
                total=total+total_item;
                double aux2= Math.rint(total*100)/100;
                total=aux2;
            }
            //visualiza el total en el label
            lbl_total.setText(Double.toString(total));
        }
        if ("40%".equals(valor)){
            porcentaje=40;
            total=0;
            for (int x=0; x < i; x++){
                double v_unitario= Double.parseDouble(matriz[x][3]);
                double v_40=v_unitario*0.40;
                v_unitario=v_unitario+v_40;
                //redondeo de numeros
                double aux= Math.rint(v_unitario*100)/100;
                v_unitario=aux;
                //se asigna el valor unitario a la tabla
                tbl_detalle.setValueAt(v_unitario, x, 2);
                int cantidad = Integer.parseInt(matriz[x][1]);
                double total_item = v_unitario*cantidad;
                //redondeo de numeros
                double aux1= Math.rint(total_item*100)/100;
                total_item=aux1;
                //se asigna el valor total de item a la tabla
                tbl_detalle.setValueAt(total_item, x, 3);
                //calcula valor total
                total=total+total_item;
                double aux2= Math.rint(total*100)/100;
                total=aux2;
           }
           //visualiza el total en el label
           lbl_total.setText(Double.toString(total)); 
        }
    }//GEN-LAST:event_Combo_precioActionPerformed

    private void btn_activarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_activarActionPerformed
        int valor =  showConfirmDialog(null,"¿Calcular porcentajes?,recuerde que no puede seleccionar mas productos");
        if(valor==0){
            Combo_precio.setEnabled(true);
            btn_buscar_productos.setEnabled(false);
            btn_activar.setEnabled(false);
            banderaborrar=true;   
           
            
       } 
       
    }//GEN-LAST:event_btn_activarActionPerformed

    private void tbl_detalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detalleMouseClicked
        if (i>0){
            if (banderaborrar==false){
                int valor =  showConfirmDialog(null,"¿Eliminar el Producto?");
                if(valor==0){
                    int posicion=0;
                    if(tbl_detalle.getSelectedRow()>=0){
                        String [] datosLeidos={
                        String.valueOf(tbl_detalle.getValueAt(tbl_detalle.getSelectedRow(),1)),
                        String.valueOf(tbl_detalle.getValueAt(tbl_detalle.getSelectedRow(),3)), 
                        };
                        for (int n=0;n<i;n++){
                            if (matriz[n][2]==datosLeidos[0])
                            {
                                posicion=n;
                            }
                        }
                        while(posicion<i-1){
                            matriz [posicion][0]=matriz[posicion+1][0];
                            //cantidad 
                            matriz [posicion][1]=matriz [posicion+1][1];
                            //detalle
                            matriz [posicion][2]=matriz [posicion+1][2];
                            //v_unitario
                            matriz [posicion][3]=matriz [posicion+1][3];
                            //v_total
                            matriz [posicion][4]=matriz [posicion+1][4];
                            posicion=posicion+1;
                        }
                        matriz [i-1][0]=null;
                                //cantidad 
                        matriz [i-1][1]=null;
                                //detalle
                        matriz [i-1][2]=null;
                                //v_unitario
                        matriz [i-1][3]=null;
                                //v_total
                        matriz [i-1][4]=null;
                        tbl_detalle.setValueAt(null, i-1, 0);
                        tbl_detalle.setValueAt(null, i-1, 1);
                        tbl_detalle.setValueAt(null, i-1, 2);
                        tbl_detalle.setValueAt(null, i-1, 3);
                        for(int x=0;x<=i-1;x++){
                            tbl_detalle.setValueAt(matriz[x][1], x, 0);
                            tbl_detalle.setValueAt(matriz[x][2], x, 1);
                            tbl_detalle.setValueAt(matriz[x][3], x, 2);
                            tbl_detalle.setValueAt(matriz[x][4], x, 3);            
                        }
                        //Disminuir el total cuando se elimina un item
                        total=total-Double.valueOf(datosLeidos[1].toString());
                        double aux= Math.rint(total*100)/100;
                        total=aux;
                        lbl_total.setText(Double.toString(total));
                        i=i-1;    
                    }
                }
            }
        }
        else {
        JOptionPane.showMessageDialog(null, "No existe productos en el detalle de la factura");
        }
        
    }//GEN-LAST:event_tbl_detalleMouseClicked
    private String capturarfecha(){
        int dia = txt_fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = txt_fecha.getCalendar().get(Calendar.MONTH)+1;
        int año = txt_fecha.getCalendar().get(Calendar.YEAR) ;
        String fecha = String.valueOf(año)+"-"+String.valueOf(mes)+"-"+String.valueOf(dia);
        return fecha;
    }
    
    private void btn_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventaActionPerformed
        if(banderacliente==true){
            if (Double.parseDouble(lbl_total.getText())>0){
                //Desactivar Botones
                btn_buscar_cliente.setEnabled(false);
                btn_buscar_productos.setEnabled(false);
                btn_activar.setEnabled(false);
                btn_venta.setEnabled(false);
                //Desactivar Botones
                String c = capturarfecha();
                String estado = "POR COBRAR";
                Cls_Cabecera cabecera=new Cls_Cabecera(Integer.parseInt(txt_codigo_factura.getText()), txt_id.getText() ,c,estado,porcentaje, Double.valueOf(lbl_total.getText()),txt_direccion.getText());
                cabecera.Guardar();
                for(int x=0;x<=i-1;x++){
                     Cls_Detalle detalle = new Cls_Detalle(Integer.parseInt(txt_codigo_factura.getText()),Integer.parseInt(matriz[x][0]),Integer.parseInt(matriz[x][1]),matriz[x][2] ,Double.valueOf(tbl_detalle.getValueAt(x, 2).toString()),Double.valueOf(tbl_detalle.getValueAt(x,3).toString()));
                     detalle.Guardar();                  
                }
                try {
                    Vistas.Reportes re = new Reportes();
                    int reporteFactura = re.reporteFactura(Integer.parseInt(txt_codigo_factura.getText()));
                } catch (JRException ex) {
                    Logger.getLogger(Frm_Factura.class.getName()).log(Level.SEVERE,null,ex);
                }catch (SQLException ex) {
                    Logger.getLogger(Frm_Factura.class.getName()).log(Level.SEVERE,null,ex);
                }
            }
            else if (Double.parseDouble(lbl_total.getText())==0){
            JOptionPane.showMessageDialog(null, "Error necesita almenos un articulo para facturar");
            }
        }
        else {
        JOptionPane.showMessageDialog(null, "Error seleccione un Cliente");
        }

      
    }//GEN-LAST:event_btn_ventaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_precio;
    private javax.swing.JButton btn_activar;
    private javax.swing.JButton btn_buscar_cliente;
    private javax.swing.JButton btn_buscar_productos;
    private javax.swing.JButton btn_venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lbl_total;
    public static javax.swing.JTable tbl_detalle;
    public static javax.swing.JTextField txt_codigo_factura;
    public static javax.swing.JTextField txt_direccion;
    private com.toedter.calendar.JDateChooser txt_fecha;
    public static javax.swing.JTextField txt_id;
    public static javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
